export const projects = [
 {id:'club',number:'01',name:'The Club at the Center of the World',short:'The Club',kind:'THE GAME',status:'In development',tag:'Unreal Engine 5.8 · Action RPG',x:.735,y:.505,image:'assets/world/club.webp',alt:'The Club at the Center of the World game banner',summary:'A divided Cape Town. An exclusive society. A revolution that starts with what you know.',body:'The ultra-rich rule the city through The Agora. You play a nobody from the Bo-Kaap, finding a way into their world through conversations, gambling, and knowledge you were never meant to have.',features:['A real Cape Town, built from geographic data and streamed with World Partition.','Graph-driven conversations, suspicion, attribute checks, and a knowledge base that changes what becomes possible.','Crowds with identities and rumors that spread from person to person.','Turn-based card combat in development, alongside an oil-painting-inspired visual direction.'],note:'Knowledge is a game mechanic: listening can change the doors that open to you.',links:[['Follow development on YouTube','https://www.youtube.com/@nikrich']]},
 {id:'conduit',entry:{x:.37,y:.59},number:'02',name:'Conduit',short:'Conduit',kind:'UNREAL PLUGIN',status:'Available on Fab',tag:'Native MCP · Editor automation',x:.335,y:.585,diagram:'conduit',summary:'A direct line from your AI agent to the Unreal Editor. Build, inspect, and play-test.',body:'Conduit embeds a Model Context Protocol server inside Unreal Editor. MCP-compatible agents can author levels, Blueprints, interfaces, materials, and gameplay without an external bridge process.',features:['Typed tools for level authoring, Blueprint graphs, UMG, materials, input, and more.','Inspect the result through screenshots and play-in-editor feedback.','Opt-in write gates and editor undo transactions for controlled authoring.'],note:'The tools are built where the work happens: inside the editor.',links:[['Get Conduit on Fab','https://www.fab.com/listings/08cdda75-e75e-4739-9c6e-0ad0a39a5fef'],['Explore the documentation','https://conduit.unrealtools.com']]},
 {id:'geoscape',entry:{x:.575,y:.455},number:'03',name:'GeoScape',short:'GeoScape',kind:'UNREAL PLUGIN',status:'Available on Fab',tag:'Real-world data · World building',x:.525,y:.36,diagram:'geoscape',summary:'One coordinate. A real-world location, ready to become your next Unreal level.',body:'GeoScape fetches OpenStreetMap buildings and roads plus global elevation, then constructs an editable, to-scale Unreal Engine location. Start with a latitude, longitude, and an area.',features:['Actual Landscape terrain with real-world elevations.','Nanite buildings and roads draped over the terrain.','Geometry organized into cells for World Partition and HLODs.'],note:'The most interesting starting point for a fictional world can be a real place.',links:[['Get GeoScape on Fab','https://www.fab.com/listings/7a4789c6-cf86-4b45-9646-01470d8f28d5'],['Explore GeoScape','https://geoscape.unrealtools.com']]},
 {id:'road',number:'04',name:'Ultimate Road Tool',short:'Road Tool',kind:'UNREAL PLUGIN',status:'Coming soon to Fab',tag:'Roads · Sidewalks · Crossings',x:.535,y:.66,image:'assets/tools/road.jpg',alt:'Ultimate Road Tool showing an Unreal Engine road intersection',summary:'Draw the streets. Shape the city. Connected roads with sidewalks, crossings, and wear.',body:'A native Unreal road-authoring system for connected, editable streets. Configure widths, lanes, sidewalks, and crossings, then choose surface styles and add wear.',features:['Connected road networks with configurable lanes and sidewalks.','Five surface styles and surface wear controls.','An experimental geographic city example with 5,850 editable roads.'],note:'The road network is the structure everything else in a city grows around.',links:[['Explore the tool & documentation','https://www.unrealtools.com/ultimate-road-tool/']]},
 {id:'deck',entry:{x:.80,y:.41},number:'05',name:'Ultimate Deck Building Toolkit',short:'Deck Toolkit',kind:'UNREAL PLUGIN',status:'Coming soon to Fab',tag:'Card authoring · Native workshop',x:.815,y:.375,image:'assets/tools/deck.jpg',alt:'Ultimate Deck Building Toolkit native Unreal workshop',summary:'Build the cards, shape a deck, and inspect how a seeded encounter plays out.',body:'A native Slate workshop for authoring card assets, building named decks, and inspecting seeded reference encounters. Made for Unreal developers who want an explicit, inspectable foundation.',features:['Card assets and named decks authored in a native editor workshop.','Seeded reference encounters, probability tools, and combat tracing.','Local deck persistence and integration documentation.'],note:'A good game system should be as interesting to inspect as it is to play.',links:[['Read the documentation','https://www.unrealtools.com/deck-toolkit/']]},
 {id:'save',entry:{x:.695,y:.365},number:'06',name:'Save Compatibility Lab',short:'Save Lab',kind:'UNREAL PLUGIN',status:'Coming soon to Fab',tag:'Capture · Compare · Verify',x:.665,y:.245,image:'assets/tools/save.jpg',alt:'Save Compatibility Lab native Unreal workbench preview',summary:'Bring save compatibility into the workbench. Capture, compare, and verify changes.',body:'A focused Unreal Engine workbench for save compatibility. Capture evidence, compare changes, and verify compatibility as a project evolves.',features:['A native Unreal workbench built around capture, comparison, and verification.','A public user guide and example project to explore the workflow.','Designed to make save compatibility an explicit part of development.'],note:'The worlds you build should still be there when players come back.',links:[['Explore Save Compatibility Lab','https://www.unrealtools.com/save-compatibility-lab/']]}
];
export const timeline = [
 ['2026 — now','Founder · PoltergeistAI','A quiet brain for loud apps. Local-first knowledge, AI agents, and deterministic LLM programming.'],
 ['2026 — now','Founder · Reduced Recipes','A lean food-tech venture that reduces recipes to what matters.'],
 ['2023 — now','Senior Solutions Engineer · Sanlam Fintech','Distributed financial-services systems. Event-driven Java, Kafka, Kinesis, Camel, AWS Lambda, DynamoDB, and domain-driven design.'],
 ['2016 — 2023','Engineer → Solutions Architect · 24.com','Seven years from full-stack developer to solutions architect. Led the News24 platform rebuild that became the backbone for 24.com brands. .NET, TypeScript, React, and Cloudflare.'],
 ['2014 — 2016','Fullstack Web Developer · PBT Insurance Technologies','ASP.NET websites and cross-platform mobile software for insurance.'],
 ['2013 — 2014','Software Developer · Nanoson Technology','Web, mobile, data, and content systems.'],
 ['2012 — 2013','Freelance Website Developer','First commercial websites and mobile apps in Cape Town.']
];
export const otherProjects = [
 ['Poltergeist','A quiet brain for loud apps.','https://getpoltergeist.com'],['Hive','Multi-agent orchestration modelled on agile teams.','https://github.com/nikrich/hungry-ghost-hive'],['Reduced Recipes','Recipes reduced to what matters.','https://reduced.recipes'],['Lockstep','Git-based source control for Unreal and Unity games.','https://github.com/nikrich/lockstep'],['Unreal Assets','Open-source assets for Unreal Engine.','https://github.com/nikrich/unreal-assets'],['AoE2 Age Up','A build-order overlay for learning Age of Empires II.','https://github.com/nikrich/aoe2-age-up'],['VST plugins','Music meets C++.','https://github.com/nikrich/vst-plugins-monorepo'],['Nexus','A TypeScript microservices reference stack.','https://github.com/nikrich?tab=repositories&q=nexus']
];
