import {projects,timeline,otherProjects} from './content.js';
import {start,move,nearest,stepToward,normalizeDiscoveries,projection} from './engine.js';
const $=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)];
const entrances=projects.map(p=>({...p,...p.entry}));
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let visited=new Set();try{visited=normalizeDiscoveries(JSON.parse(localStorage.getItem('jr-district-v1')),projects);}catch{}
let reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,player={...start},destination=null,keys=new Set(),last=0,frame=0,visible=true,returnFocus=null;
const dialog=$('#detail-dialog'),scene=$('#scene'),canvas=$('#world-canvas'),ctx=canvas.getContext('2d');
const links=items=>`<div class="detail-links">${items.map(([label,url])=>`<a href="${escape(url)}" target="_blank" rel="noopener noreferrer">${escape(label)} ↗</a>`).join('')}</div>`;
function announce(text){$('#announcement').textContent=text;}
function diagram(type){return type==='conduit'?`<svg viewBox="0 0 500 200" aria-hidden="true"><g fill="none" stroke="#bbefd8" stroke-width="1.5"><path d="M118 100H207M293 100H385" stroke-dasharray="4 5"/><rect x="15" y="68" width="103" height="64" rx="6"/><rect x="207" y="45" width="86" height="110" rx="6"/><rect x="385" y="68" width="103" height="64" rx="6"/></g><g fill="#d6ebdf" font-family="monospace" font-size="13" text-anchor="middle"><text x="67" y="105">AI AGENT</text><text x="250" y="92">NATIVE</text><text x="250" y="115">MCP</text><text x="436" y="105">UNREAL</text></g><circle cx="161" cy="100" r="4" fill="#f4b789"/><circle cx="339" cy="100" r="4" fill="#f4b789"/></svg>`:`<svg viewBox="0 0 500 200" aria-hidden="true"><g fill="none" stroke="#88cfbf" stroke-width="1"><ellipse cx="250" cy="100" rx="173" ry="67"/><ellipse cx="250" cy="100" rx="135" ry="52"/><ellipse cx="250" cy="100" rx="95" ry="36"/><ellipse cx="250" cy="100" rx="50" ry="19"/><path d="M50 100H450M250 15V185" stroke-dasharray="3 5"/></g><circle cx="250" cy="100" r="6" fill="#f4b789"/><g fill="#b7d6ce" font-family="monospace" font-size="12"><text x="305" y="160">−33.9249, 18.4241</text><text x="35" y="30">REAL WORLD → UNREAL</text></g></svg>`;}
function renderCards(){ $('#project-cards').innerHTML=projects.map(p=>`<button class="project-card" data-project="${p.id}" aria-label="Explore ${escape(p.name)}">${p.image?`<img class="card-art" src="${p.image}" alt="${escape(p.alt)}" width="640" height="330" loading="lazy">`:`<div class="card-art graph-art">${diagram(p.diagram)}</div>`}<div class="card-body"><div class="card-meta"><span>${p.number} / ${p.kind}</span><span class="state">${p.status}</span></div><h3>${p.name}</h3><p>${p.summary}</p><div class="card-bottom"><span>${p.tag}</span><span>↗</span></div></div></button>`).join('');}
function progress(){const n=visited.size;$('#quest-count').textContent=`${n} / 6 discovered`;$('#quest-progress').value=n;$('#quest-rank').textContent=n===6?'DISTRICT INSIDER':n>=3?'WORLD EXPLORER':n?'CURIOUS MIND':'NEW ARRIVAL';all('.beacon').forEach(b=>{const seen=visited.has(b.dataset.project);b.classList.toggle('visited',seen);b.querySelector('.pin').textContent=seen?'✓':projects.find(p=>p.id===b.dataset.project).number;b.setAttribute('aria-label',`${seen?'Revisit':'Discover'} ${projects.find(p=>p.id===b.dataset.project).name}`);});if(n===6)$('#begin').innerHTML='District complete <span>✧</span>';}
function discover(p){const isNew=!visited.has(p.id);visited.add(p.id);try{localStorage.setItem('jr-district-v1',JSON.stringify([...visited]));}catch{}progress();if(isNew)announce(`${p.name} discovered. ${visited.size} of 6 projects found.${visited.size===6?' You are a district insider!':''}`);}
function show(html){returnFocus=document.activeElement;keys.clear();destination=null;$('#detail-content').innerHTML=html;dialog.showModal();dialog.scrollTop=0;document.body.style.overflow='hidden';}
function openProject(id){const p=projects.find(p=>p.id===id);if(!p)return;discover(p);show(`${p.image?`<img class="detail-hero" src="${p.image}" alt="${escape(p.alt)}">`:''}<div class="detail-body"><p class="eyebrow">${p.number} / ${p.kind} · ${p.status}</p><h2 id="detail-title">${p.name}</h2><p>${p.body}</p><ul>${p.features.map(s=>`<li>${s}</li>`).join('')}</ul><div class="detail-note"><p>${p.note}</p></div>${links(p.links)}${p.id==='club'?vignette():''}<p class="discovery">✧ ${visited.size===6?'District complete. Every world starts with a little curiosity.':`${visited.size} of 6 places discovered. There’s more around the corner.`}</p><button class="outline" id="next-discovery">${visited.size===6?'Back to the district':'Find another place'} ↗</button></div>`);}
function vignette(){return `<div class="dialogue"><p class="eyebrow">AT THE DOOR / AN INTERACTIVE VIGNETTE</p><p id="dialogue-line" role="status">The door to The Agora is closed. A voice from the other side asks, “What makes you think you belong here?”</p><div id="dialogue-choices"><button data-choice="listen">Listen before answering.</button><button data-choice="ask">Ask who decides who belongs.</button><button data-choice="bluff">“Someone inside is expecting me.”</button></div><small>An original portfolio vignette inspired by the game’s premise. Not a playable build of The Club.</small></div>`;}
function choose(choice){const stories={listen:'You hear two people arguing over a name. You wait, then repeat it. A pause. The latch moves. Knowledge opened a door that confidence couldn’t.',ask:'“The people already inside,” the voice says. For a moment, neither of you speaks. You leave with a better question: who gave them that power?',bluff:'“Then you’ll know their name.” Silence. In this city, a convincing story needs something true inside it.'};$('#dialogue-line').textContent=stories[choice];$('#dialogue-choices').innerHTML='<button data-choice="restart">Try another approach ↻</button>';}
function about(){show(`<div class="detail-body"><p class="eyebrow">THE PERSON AT THE KEYBOARD / CAPE TOWN</p><h2 id="detail-title">Hi, I’m Jannik.<br><em>I like building things.</em></h2><p>I’m a Senior Solutions Engineer at Sanlam Fintech, working between modern front ends and the distributed systems behind them. Fourteen years in, I’m still happiest following an interesting problem.</p><p>Outside the day job, I build games and native Unreal tools under Hungry Ghost. The Club at the Center of the World brings together the things I keep coming back to: Cape Town, systems, stories, and worlds that respond to what you know.</p><p>I’m also the founder of PoltergeistAI and Reduced Recipes. Open source is a habit. The rest of my time goes to music, C++ VST plugins, Bevy and MonoGame experiments, and cooking through every regional curry I can find.</p><h3>What I work on</h3><p>Distributed systems and architecture. Multi-agent orchestration. Full-stack engineering. Performance, caching, and edge compute. Unreal Engine world building and gameplay systems.</p><h3>Beyond the district</h3><div class="other-projects">${otherProjects.map(([n,d,u])=>`<a href="${escape(u)}" target="_blank" rel="noopener noreferrer"><strong>${n} ↗</strong><span>${d}</span></a>`).join('')}</div><h3>Fourteen years of work</h3><div class="timeline">${timeline.map(([when,title,body])=>`<div><small>${when}</small><h3>${title}</h3><p>${body}</p></div>`).join('')}</div><h3>From people I’ve worked with</h3><blockquote class="detail-note"><p>“His passion for technology is matched by his passion for people. He leads by example and shares without hesitation.”</p><p>— Eldon Swart, Software Engineering Lead · 24.com</p></blockquote><blockquote class="detail-note"><p>“Mentor, collaborator, and a huge influence on the developer I am today.”</p><p>— Dylan Jones, Frontend Developer · 24.com</p></blockquote><h3>Notes & things in progress</h3><p>I share distributed systems, game development, and 3D work on YouTube. Current side projects include Unreal tools, the game, agent orchestration, music plugins, and an Age of Empires II build-order overlay.</p>${links([['Watch on YouTube','https://www.youtube.com/@nikrich'],['Find me on GitHub','https://github.com/nikrich'],['LinkedIn','https://www.linkedin.com/in/nikrich/']])}<button class="outline" data-panel="contact">Let’s talk ↗</button></div>`);}
function contact(){show(`<div class="detail-body"><p class="eyebrow">NO QUEST REQUIRED</p><h2 id="detail-title">Let’s make<br><em>something interesting.</em></h2><p>Unreal tools, game development, distributed systems, agent orchestration, or just engineering talk. Happy to hear from you.</p><div class="copy-row"><a class="contact-email" href="mailto:jannik811@gmail.com">jannik811@gmail.com</a><button id="copy-email">Copy email</button></div>${links([['LinkedIn','https://www.linkedin.com/in/nikrich/'],['GitHub','https://github.com/nikrich'],['YouTube','https://www.youtube.com/@nikrich']])}<p>Based in Cape Town, South Africa.</p></div>`);}
function close(){dialog.close();}
dialog.addEventListener('close',()=>{document.body.style.overflow='';keys.clear();returnFocus?.focus({preventScroll:true});});
$('.dialog-close').addEventListener('click',close);
dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}});
function travel(id){const p=entrances.find(p=>p.id===id);if(!p)return;$('#arrival').hidden=true;scene.focus({preventScroll:true});keys.clear();if(reduced){player={x:p.x,y:p.y};openProject(id);render(0);return;}destination=p;announce(`Walking to ${p.short}.`);}
document.addEventListener('click',async e=>{const panel=e.target.closest('[data-panel]');if(panel){if(dialog.open)close();panel.dataset.panel==='about'?about():contact();return;}const project=e.target.closest('[data-project]');if(project){project.classList.contains('beacon')?travel(project.dataset.project):openProject(project.dataset.project);return;}const choice=e.target.closest('[data-choice]');if(choice){if(choice.dataset.choice==='restart')$('.dialogue').outerHTML=vignette();else choose(choice.dataset.choice);return;}if(e.target.closest('#next-discovery')){close();const next=projects.find(p=>!visited.has(p.id));if(next)travel(next.id);return;}if(e.target.closest('#copy-email')){const b=$('#copy-email');try{await navigator.clipboard.writeText('jannik811@gmail.com');b.textContent='Copied';}catch{b.textContent='Select the email to copy';}return;}});
$('#beacons').innerHTML=projects.map(p=>`<button class="beacon ${p.id==='club'?'club':''}" data-project="${p.id}"><span class="pin">${p.number}</span><span class="beacon-name">${p.short}</span></button>`).join('');
$('#begin').addEventListener('click',()=>{scene.scrollIntoView({block:'center',behavior:reduced?'instant':'smooth'});travel((projects.find(p=>!visited.has(p.id))||projects[0]).id);});
$('#dismiss-arrival').addEventListener('click',()=>$('#arrival').hidden=true);
$('#reset-position').addEventListener('click',()=>{player={...start};destination=null;keys.clear();scene.focus({preventScroll:true});announce('Returned to the district entrance.');render(0);});
function motion(){document.body.classList.toggle('reduce-motion',reduced);$('#motion').textContent=`Motion: ${reduced?'off':'on'}`;$('#motion').setAttribute('aria-pressed',String(reduced));}
$('#motion').addEventListener('click',()=>{reduced=!reduced;motion();});
const keyMap={ArrowUp:'up',w:'up',ArrowDown:'down',s:'down',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};
scene.addEventListener('keydown',e=>{if(e.target!==scene)return;const k=keyMap[e.key]||keyMap[e.key.toLowerCase()];if(k){e.preventDefault();keys.add(k);destination=null;$('#arrival').hidden=true;}if(e.key.toLowerCase()==='e'){e.preventDefault();inspect();}});
window.addEventListener('keyup',e=>keys.delete(keyMap[e.key]||keyMap[e.key.toLowerCase()]));window.addEventListener('blur',()=>keys.clear());scene.addEventListener('blur',()=>keys.clear());
for(const b of all('[data-move]')){b.addEventListener('pointerdown',e=>{e.preventDefault();destination=null;keys.add(b.dataset.move);b.setPointerCapture(e.pointerId);$('#arrival').hidden=true;});for(const type of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(type,()=>keys.delete(b.dataset.move));}
function inspect(){const p=nearest(player,entrances);if(Math.hypot(player.x-p.x,player.y-p.y)<.12)openProject(p.id);else{announce(`Follow the signal to ${p.short}.`);travel(p.id);}}
$('#touch-inspect').addEventListener('click',inspect);
let w=0,h=0,view;
function resize(){w=scene.clientWidth;h=scene.clientHeight;const dpr=Math.min(devicePixelRatio||1,2);canvas.width=w*dpr;canvas.height=h*dpr;ctx?.setTransform(dpr,0,0,dpr,0,0);view=projection(w,h);all('.beacon').forEach(b=>{const p=projects.find(p=>p.id===b.dataset.project);b.style.left=`${view.x+p.x*view.width}px`;b.style.top=`${view.y+p.y*view.height}px`;});render(0);}
new ResizeObserver(resize).observe(scene);
function point(p){return {x:view.x+p.x*view.width,y:view.y+p.y*view.height};}
function render(time){if(!ctx||!view)return;ctx.clearRect(0,0,w,h);const pos=point(player),pulse=reduced?1:1+Math.sin(time*.003)*.13;const near=nearest(player,entrances);if(destination){const t=point(destination);ctx.beginPath();ctx.moveTo(pos.x,pos.y);ctx.lineTo(t.x,t.y+4);ctx.setLineDash([3,8]);ctx.strokeStyle='#c2efd970';ctx.lineWidth=1;ctx.stroke();ctx.setLineDash([]);}
// A luminous player marker, designed as game UI rather than an illustrated character.
ctx.save();ctx.translate(pos.x,pos.y);ctx.scale(1,.55);ctx.beginPath();ctx.arc(0,0,16*pulse,0,Math.PI*2);ctx.fillStyle='#bbefd815';ctx.fill();ctx.strokeStyle='#bbefd870';ctx.lineWidth=1.5;ctx.stroke();ctx.restore();ctx.shadowColor='#bbefd8';ctx.shadowBlur=16;ctx.beginPath();ctx.arc(pos.x,pos.y-10,5,0,Math.PI*2);ctx.fillStyle='#dcffed';ctx.fill();ctx.shadowBlur=0;ctx.beginPath();ctx.moveTo(pos.x,pos.y-3);ctx.lineTo(pos.x-4,pos.y+3);ctx.lineTo(pos.x+4,pos.y+3);ctx.closePath();ctx.fillStyle='#bbefd8';ctx.fill();ctx.font='10px sans-serif';ctx.textAlign='center';ctx.fillStyle='#f3fff8';ctx.fillText('YOU',pos.x,pos.y+24);
if(!destination&&Math.hypot(player.x-near.x,player.y-near.y)<.1&&!dialog.open){ctx.fillStyle='#0b1721ed';ctx.fillRect(pos.x-55,pos.y+31,110,23);ctx.fillStyle='#c6eddb';ctx.font='11px sans-serif';ctx.fillText('E · '+near.short,pos.x,pos.y+47);}}
function tick(time){const dt=Math.min((time-last)/1000||0,.035);last=time;if(visible&&!dialog.open){if(destination){const r=stepToward(player,destination,dt*.25);player=r.point;if(r.arrived){const id=destination.id;destination=null;openProject(id);}}else if(keys.size){let dx=Number(keys.has('right'))-Number(keys.has('left')),dy=Number(keys.has('down'))-Number(keys.has('up'));const norm=Math.hypot(dx,dy)||1;player=move(player,dx/norm*dt*.22,dy/norm*dt*.22);}render(time);}frame=requestAnimationFrame(tick);}
document.addEventListener('visibilitychange',()=>{visible=!document.hidden;keys.clear();if(visible){last=performance.now();if(!frame)frame=requestAnimationFrame(tick);}else{cancelAnimationFrame(frame);frame=0;}});
renderCards();progress();motion();resize();frame=requestAnimationFrame(tick);
